# Generated by Django 5.0.6 on 2024-07-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
