# Generated by Django 5.0.6 on 2024-07-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_alter_module_action_plan_alter_module_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
