# Generated by Django 5.0.6 on 2024-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parental_email',
            field=models.EmailField(max_length=234, null=True),
        ),
    ]
