# Generated by Django 5.0.6 on 2024-07-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_parental_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='calendly_link',
            field=models.CharField(blank=True, max_length=234, null=True),
        ),
    ]
